language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

env:
  global:
    - POSTGRESQL_HOST="127.0.0.1"
    - POSTGRESQL_USER="postgres"
    - POSTGRESQL_PASSWORD=""
    - POSTGRESQL_DBNAME="travis_ci_test"

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
          env: deps=beta

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - psql -c 'create database travis_ci_test;' -U postgres

install:
    - composer update --no-interaction --prefer-dist
    - if [[ $deps = 'beta' ]]; then composer config minimum-stability beta; fi;
    - if [[ $deps != 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - vendor/bin/phpunit
