language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql
  - mysql

env:
  global:
    - POSTGRESQL_HOST="127.0.0.1"
    - POSTGRESQL_USER="postgres"
    - POSTGRESQL_PASSWORD=""
    - POSTGRESQL_DBNAME="travis_ci_test"
    - MYSQL_HOST="127.0.0.1"
    - MYSQL_USER="root"
    - MYSQL_PASSWORD=""
    - MYSQL_DBNAME="travis_ci_test"

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
          env: deps=beta
        - php: 7.2
          env: deps=low
        - php: 7.2
          env: deps=beta
    allow_failures:
        - env: deps=beta
        - php: nightly

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - psql -c 'create database travis_ci_test;' -U postgres
    - mysql -e 'CREATE DATABASE travis_ci_test;'

install:
    - composer update --no-interaction --prefer-dist
    - if [[ $deps = 'beta' ]]; then composer config minimum-stability beta; fi;
    - if [[ $deps != 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi
script:
    - DB=POSTGRESQL vendor/bin/simple-phpunit
    - DB=MYSQL vendor/bin/simple-phpunit
